package fingerprint

func BuiltinRules() []Rule {
	return []Rule{
		{
			ID:             "os-windows-update",
			Name:           "Windows Update",
			Category:       CategoryOperatingSystem,
			Target:         "Windows",
			Score:          35,
			DomainSuffixes: []string{"windowsupdate.com", "download.windowsupdate.com", "update.microsoft.com"},
		},
		{
			ID:       "os-windows-connectivity",
			Name:     "Microsoft connectivity test",
			Category: CategoryOperatingSystem,
			Target:   "Windows",
			Score:    20,
			Domains:  []string{"msftconnecttest.com", "www.msftconnecttest.com", "msftncsi.com"},
		},
		{
			ID:             "vendor-microsoft",
			Name:           "Microsoft domains",
			Category:       CategoryVendor,
			Target:         "Microsoft",
			Score:          15,
			DomainSuffixes: []string{"microsoft.com", "live.com", "office.com"},
		},
		{
			ID:       "os-android-connectivity",
			Name:     "Android connectivity check",
			Category: CategoryOperatingSystem,
			Target:   "Android",
			Score:    35,
			Domains:  []string{"connectivitycheck.gstatic.com", "android.clients.google.com"},
		},
		{
			ID:             "os-android-google-play",
			Name:           "Android Google Play services",
			Category:       CategoryOperatingSystem,
			Target:         "Android",
			Score:          25,
			DomainSuffixes: []string{"play.googleapis.com", "mtalk.google.com"},
		},
		{
			ID:             "device-mobile-android",
			Name:           "Android mobile behaviour",
			Category:       CategoryDeviceType,
			Target:         "Mobile phone",
			Score:          35,
			DomainSuffixes: []string{"mtalk.google.com", "play.googleapis.com"},
		},
		{
			ID:             "vendor-google",
			Name:           "Google domains",
			Category:       CategoryVendor,
			Target:         "Google",
			Score:          15,
			DomainSuffixes: []string{"google.com", "googleapis.com", "gstatic.com"},
		},
		{
			ID:             "os-apple",
			Name:           "Apple platform services",
			Category:       CategoryOperatingSystem,
			Target:         "Apple/iOS",
			Score:          35,
			DomainSuffixes: []string{"apple.com", "icloud.com", "mzstatic.com", "push.apple.com"},
		},
		{
			ID:             "device-apple-mobile",
			Name:           "Apple mobile behaviour",
			Category:       CategoryDeviceType,
			Target:         "Mobile phone",
			Score:          25,
			DomainSuffixes: []string{"push.apple.com", "icloud.com"},
		},
		{
			ID:             "vendor-apple",
			Name:           "Apple domains",
			Category:       CategoryVendor,
			Target:         "Apple",
			Score:          20,
			DomainSuffixes: []string{"apple.com", "icloud.com"},
		},
		{
			ID:             "os-linux-ubuntu",
			Name:           "Ubuntu package repositories",
			Category:       CategoryOperatingSystem,
			Target:         "Linux",
			Score:          25,
			DomainSuffixes: []string{"ubuntu.com", "archive.ubuntu.com", "security.ubuntu.com"},
		},
		{
			ID:             "os-linux-debian",
			Name:           "Debian package repositories",
			Category:       CategoryOperatingSystem,
			Target:         "Linux",
			Score:          20,
			DomainSuffixes: []string{"debian.org", "deb.debian.org"},
		},
		{
			ID:             "device-server-linux",
			Name:           "Linux server update behaviour",
			Category:       CategoryDeviceType,
			Target:         "Server",
			Score:          20,
			DomainSuffixes: []string{"ubuntu.com", "debian.org", "docker.com"},
		},
		{
			ID:             "software-home-assistant",
			Name:           "Home Assistant",
			Category:       CategorySoftware,
			Target:         "Home Assistant",
			Score:          45,
			DomainSuffixes: []string{"home-assistant.io", "nabucasa.com"},
		},
		{
			ID:             "software-docker",
			Name:           "Docker",
			Category:       CategorySoftware,
			Target:         "Docker",
			Score:          35,
			DomainSuffixes: []string{"docker.com", "docker.io"},
		},
		{
			ID:             "software-kubernetes",
			Name:           "Kubernetes",
			Category:       CategorySoftware,
			Target:         "Kubernetes",
			Score:          35,
			DomainSuffixes: []string{"k8s.io", "kubernetes.io"},
		},
		{
			ID:             "software-plex",
			Name:           "Plex",
			Category:       CategorySoftware,
			Target:         "Plex",
			Score:          45,
			DomainSuffixes: []string{"plex.tv"},
		},
		{
			ID:             "software-jellyfin",
			Name:           "Jellyfin",
			Category:       CategorySoftware,
			Target:         "Jellyfin",
			Score:          45,
			DomainSuffixes: []string{"jellyfin.org"},
		},
		{
			ID:             "software-steam",
			Name:           "Steam",
			Category:       CategorySoftware,
			Target:         "Steam",
			Score:          35,
			DomainSuffixes: []string{"steampowered.com", "steamcontent.com"},
		},
		{
			ID:             "software-tailscale",
			Name:           "Tailscale",
			Category:       CategorySoftware,
			Target:         "Tailscale",
			Score:          45,
			DomainSuffixes: []string{"tailscale.com", "tailscale.io"},
		},
		{
			ID:             "infra-dns",
			Name:           "DNS infrastructure",
			Category:       CategoryInfrastructure,
			Target:         "DNS server",
			Score:          30,
			DomainSuffixes: []string{"root-servers.net", "arpa"},
		},
		{
			ID:             "infra-router-vendor",
			Name:           "Network equipment vendor",
			Category:       CategoryInfrastructure,
			Target:         "Network equipment",
			Score:          25,
			DomainSuffixes: []string{"ui.com", "ubnt.com", "mikrotik.com", "tplinkcloud.com"},
		},
	}
}
